name: DCO commit signoff check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-commit-message:
    name: Check commit message
    runs-on: ubuntu-latest
    # exclude PR merge commits from sign-off checking workflow
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    steps:
      - name: Searching for "Signed-off"
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: 'Signed-off-by: \S+( \S+)* <\S+@\S+>'
          error: "Commit message does not include DCO signature; please see CONTRIBUTING.md."
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
